print('WORLD GAME')

first = input('what is your first name?\n')
last = input('what is your last name?\n')
class_= input('What is your Class?\n')
print('Please Enter The Following')
adjective = input('Enter an adjective\n')
animal = input('Enter an animal\n')
verb_1 = input('Enter a verb\n')
exclamation = input('Enter an exclamation mark\n')
verb_2 = input('enter a verb\n')
verb_3 = input('enter a verb\n')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} , {animal} , {verb_1}')
print(f'down the hallway. {exclamation}!')
print(f'I yelled. But all I could think to do was to {verb_2}, over and over.')
print(f'Miraculously, that caused it to stop, but not before it tried to {verb_3} right in front of my family.\n')
print('Above is a word game presented by')
print(first,last,  class_)